version: '3.8'

services:

  backend:
    build:
      context: .
      args:
        - APP_PATH=${APP_PATH}
        - ENTRYPOINT=${ENTRYPOINT}
        - INTERNAL_PORT=${INTERNAL_PORT}
        - EXTERNAL_PORT=${EXTERNAL_PORT}
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"